// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MenuTFT

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_status_bar;
extern lv_obj_t * ui_wifistatuslabel;
extern lv_obj_t * ui_TabView1;
extern lv_obj_t * ui_Dashboard;
extern lv_obj_t * ui_temp_label;
extern lv_obj_t * ui_hum_label;
extern lv_obj_t * ui_moisture_label;
extern lv_obj_t * ui_lux_label;
extern lv_obj_t * ui_Menu;
extern lv_obj_t * ui_menu_list;
extern void ui_event_btn_env(lv_event_t * e);
extern lv_obj_t * ui_btn_env;
extern lv_obj_t * ui_tempenv;
extern void ui_event_lighting_schedule(lv_event_t * e);
extern lv_obj_t * ui_lighting_schedule;
extern lv_obj_t * ui_light;
extern void ui_event_Display_Settings(lv_event_t * e);
extern lv_obj_t * ui_Display_Settings;
extern lv_obj_t * ui_disp;
extern void ui_event_Network_Settings(lv_event_t * e);
extern lv_obj_t * ui_Network_Settings;
extern lv_obj_t * ui_net;
extern lv_obj_t * ui_env_page;
extern void ui_event_btn_back_env(lv_event_t * e);
extern lv_obj_t * ui_btn_back_env;
extern lv_obj_t * ui_back;
extern lv_obj_t * ui_temp_slider;
extern lv_obj_t * ui_hum_slider;
extern lv_obj_t * ui_soil_slider;
extern lv_obj_t * ui_lux_slider;
extern lv_obj_t * ui_lighting_page;
extern void ui_event_btn_back_light(lv_event_t * e);
extern lv_obj_t * ui_btn_back_light;
extern lv_obj_t * ui_back2;
extern lv_obj_t * ui_display_page;
extern void ui_event_btn_back_display(lv_event_t * e);
extern lv_obj_t * ui_btn_back_display;
extern lv_obj_t * ui_back3;
extern lv_obj_t * ui_network_page;
extern void ui_event_btn_back_network(lv_event_t * e);
extern lv_obj_t * ui_btn_back_network;
extern lv_obj_t * ui_back4;
// CUSTOM VARIABLES
extern lv_obj_t * uic_status_bar;
extern lv_obj_t * uic_temp_label;
extern lv_obj_t * uic_hum_label;
extern lv_obj_t * uic_moisture_label;
extern lv_obj_t * uic_menu_list;
extern lv_obj_t * uic_btn_env;
extern lv_obj_t * uic_lighting_schedule;
extern lv_obj_t * uic_Display_Settings;
extern lv_obj_t * uic_Network_Settings;
extern lv_obj_t * uic_env_page;
extern lv_obj_t * uic_btn_back;
extern lv_obj_t * uic_temp_slider;
extern lv_obj_t * uic_hum_slider;
extern lv_obj_t * uic_lighting_page;
extern lv_obj_t * uic_display_page;
extern lv_obj_t * uic_network_page;
extern lv_obj_t * uic_btn_back_network;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

