// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MenuTFT

#ifndef _MENUTFT_UI_H
#define _MENUTFT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_waterdroplet_white_1_png);    // assets/waterdroplet_white_1.png
LV_IMG_DECLARE(ui_img_temp_icon_1_png);    // assets/temp_icon_1.png
LV_IMG_DECLARE(ui_img_humidity_icon_3_png);    // assets/humidity_icon_3.png
LV_IMG_DECLARE(ui_img_sun_white_1_png);    // assets/sun_white_1.png
LV_IMG_DECLARE(ui_img_3c4ba157_white_32x32_png);    // assets/3c4ba157_white_32x32.png
LV_IMG_DECLARE(ui_img_white_png_32x32_png);    // assets/white_png_32x32.png
LV_IMG_DECLARE(ui_img_175872_white_32x32_png);    // assets/175872_white_32x32.png
LV_IMG_DECLARE(ui_img_sun_white_short_rays_32x32_png);    // assets/sun_white_short_rays_32x32.png
LV_IMG_DECLARE(ui_img_water_pump_white_32x32_png);    // assets/water_pump_white_32x32.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
