// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Corn Squareline

#include "ui_events.h"

void Moisture_range_slider_changed(lv_event_t * e)
{
    (void)e;
    // Your code here
}
