// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MY SQUARELINE

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t *ui_Screen1;
extern lv_obj_t *ui_status_bar;
extern lv_obj_t *ui_wifistatuslabel;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Dashboard;
extern lv_obj_t *ui_temp_label;
extern lv_obj_t *ui_hum_label;
extern lv_obj_t *ui_moisture_label;
extern lv_obj_t *ui_lux_label;
extern lv_obj_t *ui_Menu;
extern lv_obj_t *ui_menu_list;
extern void ui_event_btn_env( lv_event_t * e);
extern lv_obj_t *ui_btn_env;
extern lv_obj_t *ui_tempenv;
extern void ui_event_lighting_schedule( lv_event_t * e);
extern lv_obj_t *ui_lighting_schedule;
extern lv_obj_t *ui_light;
extern void ui_event_Display_Settings( lv_event_t * e);
extern lv_obj_t *ui_Display_Settings;
extern lv_obj_t *ui_disp;
extern void ui_event_Network_Settings( lv_event_t * e);
extern lv_obj_t *ui_Network_Settings;
extern lv_obj_t *ui_net;
extern lv_obj_t *ui_env_page;
extern lv_obj_t *ui_temp_slider;
extern lv_obj_t *ui_hum_slider;
extern void ui_event_soil_slider( lv_event_t * e);
extern lv_obj_t *ui_soil_slider;
extern lv_obj_t *ui_TempLabel;
extern lv_obj_t *ui_HumidityLabel;
extern lv_obj_t *ui_MoistureLabel1;
extern lv_obj_t *ui_Soil_moisture_Icon;
extern lv_obj_t *ui_Temperature_Icon;
extern lv_obj_t *ui_Humidity_Icon;
extern lv_obj_t *ui_Lower_Limit;
extern lv_obj_t *ui_Upper_Limit;
extern lv_obj_t *ui_LowerMoistLimit;
extern lv_obj_t *ui_lighting_page;
extern lv_obj_t *ui_lux_slider;
extern lv_obj_t *ui_LuxLabel;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_display_page;
extern void ui_event_btn_back_global( lv_event_t * e);
extern lv_obj_t *ui_btn_back_global;
extern lv_obj_t *ui_back;
// CUSTOM VARIABLES
extern lv_obj_t *ui_status_bar;
extern lv_obj_t *ui_wifistatuslabel;
extern lv_obj_t *ui_TabView1;
extern lv_obj_t *ui_Dashboard;
extern lv_obj_t *ui_temp_label;
extern lv_obj_t *ui_hum_label;
extern lv_obj_t *ui_moisture_label;
extern lv_obj_t *ui_lux_label;
extern lv_obj_t *ui_Menu;
extern lv_obj_t *ui_menu_list;
extern lv_obj_t *ui_btn_env;
extern lv_obj_t *ui_tempenv;
extern lv_obj_t *ui_lighting_schedule;
extern lv_obj_t *ui_light;
extern lv_obj_t *ui_Display_Settings;
extern lv_obj_t *ui_disp;
extern lv_obj_t *ui_Network_Settings;
extern lv_obj_t *ui_net;
extern lv_obj_t *ui_env_page;
extern lv_obj_t *ui_temp_slider;
extern lv_obj_t *ui_hum_slider;
extern lv_obj_t *ui_soil_slider;
extern lv_obj_t *ui_lighting_page;
extern lv_obj_t *ui_lux_slider;
extern lv_obj_t *ui_display_page;
extern lv_obj_t *ui_btn_back_global;
extern lv_obj_t *ui_back;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

