// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MY SQUARELINE

#include "ui.h"

void open_wifi_scanner_cb(lv_event_t * e)
{
	// Your code here
}

void global_back_cb(lv_event_t * e)
{
	// Your code here
}

void Moisture_range_slider_changed(lv_event_t * e)
{
	lv_obj_t * slider = lv_event_get_target(e);

    int32_t left  = lv_bar_get_start_value(slider);
    int32_t right = lv_slider_get_value(slider);

    lv_label_set_text_fmt(ui_Label1, "%d - %d", (int)left, (int)right);
}
