// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MenuTFT

#include "ui.h"

void open_wifi_scanner_cb(lv_event_t * e)
{
	// Your code here
}

void Moisture_range_slider_changed(lv_event_t * e)
{
	// Your code here
}

void global_back_cb(lv_event_t * e)
{
	// Your code here
}
