// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MenuTFT

#include "../ui.h"

lv_obj_t * ui_back;
lv_obj_t * ui_btn_back_global;
lv_obj_t * ui_display_page;
lv_obj_t * ui_lux_slider;
lv_obj_t * ui_lighting_page;
lv_obj_t * ui_soil_slider;
lv_obj_t * ui_hum_slider;
lv_obj_t * ui_temp_slider;
lv_obj_t * ui_env_page;
lv_obj_t * ui_net;
lv_obj_t * ui_Network_Settings;
lv_obj_t * ui_disp;
lv_obj_t * ui_Display_Settings;
lv_obj_t * ui_light;
lv_obj_t * ui_lighting_schedule;
lv_obj_t * ui_tempenv;
lv_obj_t * ui_btn_env;
lv_obj_t * ui_menu_list;
lv_obj_t * ui_Menu;
lv_obj_t * ui_lux_label;
lv_obj_t * ui_moisture_label;
lv_obj_t * ui_hum_label;
lv_obj_t * ui_temp_label;
lv_obj_t * ui_Dashboard;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_wifistatuslabel;
lv_obj_t * ui_status_bar;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_status_bar = NULL;
lv_obj_t * ui_wifistatuslabel = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_Dashboard = NULL;
lv_obj_t * ui_temp_label = NULL;
lv_obj_t * ui_hum_label = NULL;
lv_obj_t * ui_moisture_label = NULL;
lv_obj_t * ui_lux_label = NULL;
lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_menu_list = NULL;
lv_obj_t * ui_btn_env = NULL;
lv_obj_t * ui_tempenv = NULL;
lv_obj_t * ui_lighting_schedule = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_Override = NULL;
lv_obj_t * ui_disp = NULL;
lv_obj_t * ui_Network_Settings = NULL;
lv_obj_t * ui_net = NULL;
lv_obj_t * ui_env_page = NULL;
lv_obj_t * ui_Soil_moisture_slider = NULL;
lv_obj_t * ui_Temp_slider1 = NULL;
lv_obj_t * ui_Humidity_slider_ = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_HumidityLabel = NULL;
lv_obj_t * ui_MoistureLabel1 = NULL;
lv_obj_t * ui_pHlabel = NULL;
lv_obj_t * ui_Soil_moisture_Icon = NULL;
lv_obj_t * ui_Temperature_Icon = NULL;
lv_obj_t * ui_Humidity_Icon = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_lighting_page = NULL;
lv_obj_t * ui_lux_slider = NULL;
lv_obj_t * ui_LuxLabel = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Override_Page = NULL;
lv_obj_t * ui_cold_image = NULL;
lv_obj_t * ui_Peltier_Controls = NULL;
lv_obj_t * ui_Cold_button = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_heat_image = NULL;
lv_obj_t * ui_Peltier_Controls1 = NULL;
lv_obj_t * ui_heat_button = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Mist_Label = NULL;
lv_obj_t * ui_mist_image = NULL;
lv_obj_t * ui_mist_button = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_UV_Light = NULL;
lv_obj_t * ui_light_image = NULL;
lv_obj_t * ui_light_level_1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_light_level_2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_light_level_3 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_brighter_light = NULL;
lv_obj_t * ui_Water_Pump = NULL;
lv_obj_t * ui_Water_Pump_Image = NULL;
lv_obj_t * ui_water_pump_button = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_btn_back_global = NULL;
lv_obj_t * ui_back = NULL;
// event funtions
void ui_event_btn_env(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_env_page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_lighting_schedule(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_lighting_page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Override(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Override_Page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Network_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        open_wifi_scanner_cb(e);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Humidity_slider_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Moisture_range_slider_changed(e);
    }
}

void ui_event_btn_back_global(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        global_back_cb(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_bar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_status_bar);
    lv_obj_set_width(ui_status_bar, 320);
    lv_obj_set_height(ui_status_bar, 30);
    lv_obj_set_align(ui_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistatuslabel = lv_label_create(ui_status_bar);
    lv_obj_set_width(ui_wifistatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistatuslabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifistatuslabel, "LV_SYMBOL_WIFI");

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 480);
    lv_obj_set_height(ui_TabView1, 290);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags

    ui_Dashboard = lv_tabview_add_tab(ui_TabView1, "Dashboard");
    lv_obj_clear_flag(ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_temp_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_label, 0);
    lv_obj_set_y(ui_temp_label, 20);
    lv_obj_set_align(ui_temp_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_temp_label, "Temp: --.- °F");

    ui_hum_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_hum_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hum_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hum_label, 0);
    lv_obj_set_y(ui_hum_label, 60);
    lv_obj_set_align(ui_hum_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_hum_label, "Humidity: -- %");

    ui_moisture_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_moisture_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture_label, 0);
    lv_obj_set_y(ui_moisture_label, 100);
    lv_obj_set_align(ui_moisture_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_moisture_label, "Moisture: -- %");

    ui_lux_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lux_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lux_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lux_label, 0);
    lv_obj_set_y(ui_lux_label, 140);
    lv_obj_set_align(ui_lux_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lux_label, "Light: -- lux");

    ui_Menu = lv_tabview_add_tab(ui_TabView1, "Menu");
    lv_obj_set_flex_flow(ui_Menu, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Menu, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_menu_list = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_menu_list);
    lv_obj_set_width(ui_menu_list, lv_pct(100));
    lv_obj_set_height(ui_menu_list, lv_pct(100));
    lv_obj_set_align(ui_menu_list, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menu_list, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menu_list, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_menu_list, LV_DIR_VER);

    ui_btn_env = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_btn_env, 50);
    lv_obj_set_width(ui_btn_env, lv_pct(100));
    lv_obj_set_align(ui_btn_env, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_env, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_env, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempenv = lv_label_create(ui_btn_env);
    lv_obj_set_width(ui_tempenv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempenv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempenv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempenv, "Environment Controls");

    ui_lighting_schedule = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_lighting_schedule, 50);
    lv_obj_set_width(ui_lighting_schedule, lv_pct(100));
    lv_obj_set_x(ui_lighting_schedule, 8);
    lv_obj_set_y(ui_lighting_schedule, 29);
    lv_obj_set_align(ui_lighting_schedule, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lighting_schedule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lighting_schedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light = lv_label_create(ui_lighting_schedule);
    lv_obj_set_width(ui_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);
    lv_label_set_text(ui_light, "Lighting Schedule");

    ui_Override = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_Override, 50);
    lv_obj_set_width(ui_Override, lv_pct(100));
    lv_obj_set_x(ui_Override, 8);
    lv_obj_set_y(ui_Override, 29);
    lv_obj_set_align(ui_Override, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Override, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Override, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_disp = lv_label_create(ui_Override);
    lv_obj_set_width(ui_disp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_disp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_disp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_disp, "Override");

    ui_Network_Settings = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_Network_Settings, 50);
    lv_obj_set_width(ui_Network_Settings, lv_pct(100));
    lv_obj_set_x(ui_Network_Settings, 8);
    lv_obj_set_y(ui_Network_Settings, 29);
    lv_obj_set_align(ui_Network_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Network_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_net = lv_label_create(ui_Network_Settings);
    lv_obj_set_width(ui_net, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_net, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_net, LV_ALIGN_CENTER);
    lv_label_set_text(ui_net, "Network Settings");

    ui_env_page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_env_page);
    lv_obj_set_width(ui_env_page, lv_pct(100));
    lv_obj_set_height(ui_env_page, lv_pct(100));
    lv_obj_set_align(ui_env_page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_env_page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_env_page, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Soil_moisture_slider = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_Soil_moisture_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_Soil_moisture_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Soil_moisture_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Soil_moisture_slider, 0, LV_ANIM_OFF);
        lv_obj_set_width(ui_Soil_moisture_slider, 180);
    lv_obj_set_height(ui_Soil_moisture_slider, 10);
        lv_obj_set_x(ui_Soil_moisture_slider, 0);
        lv_obj_set_y(ui_Soil_moisture_slider, -60);
    lv_obj_set_align(ui_Soil_moisture_slider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Soil_moisture_slider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Soil_moisture_slider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Temp_slider1 = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_Temp_slider1, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_Temp_slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Temp_slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Temp_slider1, 0,
                                                                                                 LV_ANIM_OFF);
    lv_obj_set_width(ui_Temp_slider1, 180);
    lv_obj_set_height(ui_Temp_slider1, 10);
    lv_obj_set_x(ui_Temp_slider1, 0);
    lv_obj_set_y(ui_Temp_slider1, 10);
    lv_obj_set_align(ui_Temp_slider1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Temp_slider1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Temp_slider1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_Humidity_slider_ = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_Humidity_slider_, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_Humidity_slider_, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Humidity_slider_) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Humidity_slider_, 100,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_width(ui_Humidity_slider_, 180);
    lv_obj_set_height(ui_Humidity_slider_, 10);
    lv_obj_set_x(ui_Humidity_slider_, 0);
    lv_obj_set_y(ui_Humidity_slider_, 80);
    lv_obj_set_align(ui_Humidity_slider_, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Humidity_slider_, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Humidity_slider_, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_TempLabel = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 18);
    lv_obj_set_y(ui_TempLabel, -10);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temperature");

    ui_HumidityLabel = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel, 18);
    lv_obj_set_y(ui_HumidityLabel, 60);
    lv_obj_set_align(ui_HumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel, "Humidity");

    ui_MoistureLabel1 = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_MoistureLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoistureLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoistureLabel1, 18);
    lv_obj_set_y(ui_MoistureLabel1, -80);
    lv_obj_set_align(ui_MoistureLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoistureLabel1, "Soil Moisture");

    ui_pHlabel = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_pHlabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_pHlabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_pHlabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_pHlabel, "pH Level");

    ui_Soil_moisture_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Soil_moisture_Icon, &ui_img_waterdroplet_white_1_png);
    lv_obj_set_width(ui_Soil_moisture_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Soil_moisture_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Soil_moisture_Icon, -108);
    lv_obj_set_y(ui_Soil_moisture_Icon, -83);
    lv_obj_set_align(ui_Soil_moisture_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Soil_moisture_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Soil_moisture_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Soil_moisture_Icon, 260);

    ui_Temperature_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Temperature_Icon, &ui_img_temp_icon_1_png);
    lv_obj_set_width(ui_Temperature_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_Icon, -108);
    lv_obj_set_y(ui_Temperature_Icon, -13);
    lv_obj_set_align(ui_Temperature_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Temperature_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Temperature_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Temperature_Icon, 260);

    ui_Humidity_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Humidity_Icon, &ui_img_humidity_icon_3_png);
    lv_obj_set_width(ui_Humidity_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity_Icon, -108);
    lv_obj_set_y(ui_Humidity_Icon, 57);
    lv_obj_set_align(ui_Humidity_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Humidity_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Humidity_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Humidity_Icon, 300);

    ui_Bar1 = lv_bar_create(ui_env_page);
    lv_bar_set_range(ui_Bar1, 0, 14);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, 0);
    lv_obj_set_y(ui_Bar1, 20);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    ui_Image2 = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Image2, &ui_img_white_ph_icon_1_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -50);
    lv_obj_set_y(ui_Image2, -10);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image2, 250);

    ui_lighting_page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_lighting_page);
    lv_obj_set_width(ui_lighting_page, lv_pct(100));
    lv_obj_set_height(ui_lighting_page, lv_pct(100));
    lv_obj_set_align(ui_lighting_page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lighting_page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_lighting_page, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_lux_slider = lv_slider_create(ui_lighting_page);
    lv_slider_set_mode(ui_lux_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_lux_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_lux_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_lux_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_lux_slider, 150);
    lv_obj_set_height(ui_lux_slider, 10);
    lv_obj_set_align(ui_lux_slider, LV_ALIGN_CENTER);

    ui_LuxLabel = lv_label_create(ui_lighting_page);
    lv_obj_set_width(ui_LuxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxLabel, 0);
    lv_obj_set_y(ui_LuxLabel, -20);
    lv_obj_set_align(ui_LuxLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxLabel, "Lux");

    ui_Image1 = lv_img_create(ui_lighting_page);
    lv_img_set_src(ui_Image1, &ui_img_sun_white_1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 110);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 400);

    ui_Override_Page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_Override_Page);
    lv_obj_set_width(ui_Override_Page, lv_pct(100));
    lv_obj_set_height(ui_Override_Page, lv_pct(100));
    lv_obj_set_x(ui_Override_Page, 0);
    lv_obj_set_y(ui_Override_Page, 2);
    lv_obj_set_align(ui_Override_Page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Override_Page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Override_Page, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_cold_image = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_cold_image, &ui_img_3c4ba157_white_32x32_png);
    lv_obj_set_width(ui_cold_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_cold_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_cold_image, -200);
    lv_obj_set_y(ui_cold_image, -60);
    lv_obj_set_align(ui_cold_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_cold_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_cold_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Peltier_Controls = lv_label_create(ui_Override_Page);
    lv_obj_set_width(ui_Peltier_Controls, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peltier_Controls, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peltier_Controls, -130);
    lv_obj_set_y(ui_Peltier_Controls, -90);
    lv_obj_set_align(ui_Peltier_Controls, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Peltier_Controls, "Peltier Controls");

    ui_Cold_button = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_Cold_button, 100);
    lv_obj_set_height(ui_Cold_button, 40);
    lv_obj_set_x(ui_Cold_button, -130);
    lv_obj_set_y(ui_Cold_button, -60);
    lv_obj_set_align(ui_Cold_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Cold_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Cold_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Cold_button);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "cooling");

    ui_heat_image = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_heat_image, &ui_img_white_png_32x32_png);
    lv_obj_set_width(ui_heat_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heat_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_heat_image, -200);
    lv_obj_set_y(ui_heat_image, -7);
    lv_obj_set_align(ui_heat_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heat_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_heat_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Peltier_Controls1 = lv_label_create(ui_Override_Page);
    lv_obj_set_width(ui_Peltier_Controls1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Peltier_Controls1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Peltier_Controls1, -130);
    lv_obj_set_y(ui_Peltier_Controls1, -90);
    lv_obj_set_align(ui_Peltier_Controls1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Peltier_Controls1, "Peltier Controls");

    ui_heat_button = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_heat_button, 100);
    lv_obj_set_height(ui_heat_button, 40);
    lv_obj_set_x(ui_heat_button, -130);
    lv_obj_set_y(ui_heat_button, -7);
    lv_obj_set_align(ui_heat_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_heat_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_heat_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_heat_button);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "heating");

    ui_Mist_Label = lv_label_create(ui_Override_Page);
    lv_obj_set_width(ui_Mist_Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Mist_Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Mist_Label, -130);
    lv_obj_set_y(ui_Mist_Label, 40);
    lv_obj_set_align(ui_Mist_Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Mist_Label, "Mist");

    ui_mist_image = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_mist_image, &ui_img_175872_white_32x32_png);
    lv_obj_set_width(ui_mist_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_mist_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_mist_image, -200);
    lv_obj_set_y(ui_mist_image, 70);
    lv_obj_set_align(ui_mist_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mist_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_mist_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mist_button = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_mist_button, 100);
    lv_obj_set_height(ui_mist_button, 40);
    lv_obj_set_x(ui_mist_button, -130);
    lv_obj_set_y(ui_mist_button, 70);
    lv_obj_set_align(ui_mist_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_mist_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_mist_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_mist_button);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "test");

    ui_UV_Light = lv_label_create(ui_Override_Page);
    lv_obj_set_width(ui_UV_Light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UV_Light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UV_Light, 130);
    lv_obj_set_y(ui_UV_Light, -90);
    lv_obj_set_align(ui_UV_Light, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UV_Light, "Light control");

    ui_light_image = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_light_image, &ui_img_sun_white_1_png);
    lv_obj_set_width(ui_light_image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light_image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_light_image, 70);
    lv_obj_set_y(ui_light_image, -60);
    lv_obj_set_align(ui_light_image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_light_image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light_level_1 = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_light_level_1, 70);
    lv_obj_set_height(ui_light_level_1, 20);
    lv_obj_set_x(ui_light_level_1, 130);
    lv_obj_set_y(ui_light_level_1, -60);
    lv_obj_set_align(ui_light_level_1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_level_1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_light_level_1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_light_level_1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "LVL 1");

    ui_light_level_2 = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_light_level_2, 70);
    lv_obj_set_height(ui_light_level_2, 20);
    lv_obj_set_x(ui_light_level_2, 130);
    lv_obj_set_y(ui_light_level_2, -30);
    lv_obj_set_align(ui_light_level_2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_level_2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_light_level_2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_light_level_2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "LVL 2");

    ui_light_level_3 = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_light_level_3, 70);
    lv_obj_set_height(ui_light_level_3, 20);
    lv_obj_set_x(ui_light_level_3, 130);
    lv_obj_set_y(ui_light_level_3, 0);
    lv_obj_set_align(ui_light_level_3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_light_level_3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_light_level_3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_light_level_3);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "LVL 3");

    ui_brighter_light = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_brighter_light, &ui_img_sun_white_short_rays_32x32_png);
    lv_obj_set_width(ui_brighter_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_brighter_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_brighter_light, 70);
    lv_obj_set_y(ui_brighter_light, 0);
    lv_obj_set_align(ui_brighter_light, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_brighter_light, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brighter_light, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Water_Pump = lv_label_create(ui_Override_Page);
    lv_obj_set_width(ui_Water_Pump, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Pump, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Pump, 130);
    lv_obj_set_y(ui_Water_Pump, 40);
    lv_obj_set_align(ui_Water_Pump, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Water_Pump, "Water Pump");

    ui_Water_Pump_Image = lv_img_create(ui_Override_Page);
    lv_img_set_src(ui_Water_Pump_Image, &ui_img_water_pump_white_32x32_png);
    lv_obj_set_width(ui_Water_Pump_Image, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Water_Pump_Image, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Water_Pump_Image, 70);
    lv_obj_set_y(ui_Water_Pump_Image, 70);
    lv_obj_set_align(ui_Water_Pump_Image, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Water_Pump_Image, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Water_Pump_Image, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_water_pump_button = lv_btn_create(ui_Override_Page);
    lv_obj_set_width(ui_water_pump_button, 100);
    lv_obj_set_height(ui_water_pump_button, 40);
    lv_obj_set_x(ui_water_pump_button, 140);
    lv_obj_set_y(ui_water_pump_button, 70);
    lv_obj_set_align(ui_water_pump_button, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_water_pump_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_water_pump_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_water_pump_button);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "test");

    ui_btn_back_global = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btn_back_global, 100);
    lv_obj_set_height(ui_btn_back_global, 22);
    lv_obj_set_x(ui_btn_back_global, 3);
    lv_obj_set_y(ui_btn_back_global, 3);
    lv_obj_add_flag(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_back_global, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back = lv_label_create(ui_btn_back_global);
    lv_obj_set_width(ui_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_back, "< Back");

    lv_obj_add_event_cb(ui_btn_env, ui_event_btn_env, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lighting_schedule, ui_event_lighting_schedule, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Override, ui_event_Override, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Network_Settings, ui_event_Network_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Humidity_slider_, ui_event_Humidity_slider_, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_back_global, ui_event_btn_back_global, LV_EVENT_ALL, NULL);
    ui_status_bar = ui_status_bar;
    ui_wifistatuslabel = ui_wifistatuslabel;
    ui_TabView1 = ui_TabView1;
    ui_Dashboard = ui_Dashboard;
    ui_temp_label = ui_temp_label;
    ui_hum_label = ui_hum_label;
    ui_moisture_label = ui_moisture_label;
    ui_lux_label = ui_lux_label;
    ui_Menu = ui_Menu;
    ui_menu_list = ui_menu_list;
    ui_btn_env = ui_btn_env;
    ui_tempenv = ui_tempenv;
    ui_lighting_schedule = ui_lighting_schedule;
    ui_light = ui_light;
    ui_Display_Settings = ui_Override;
    ui_disp = ui_disp;
    ui_Network_Settings = ui_Network_Settings;
    ui_net = ui_net;
    ui_env_page = ui_env_page;
    ui_temp_slider = ui_Soil_moisture_slider;
    ui_hum_slider = ui_Temp_slider1;
    ui_soil_slider = ui_Humidity_slider_;
    ui_lighting_page = ui_lighting_page;
    ui_lux_slider = ui_lux_slider;
    ui_display_page = ui_Override_Page;
    ui_btn_back_global = ui_btn_back_global;
    ui_back = ui_back;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_status_bar = NULL;
    ui_status_bar = NULL;
    ui_wifistatuslabel = NULL;
    ui_wifistatuslabel = NULL;
    ui_TabView1 = NULL;
    ui_TabView1 = NULL;
    ui_Dashboard = NULL;
    ui_Dashboard = NULL;
    ui_temp_label = NULL;
    ui_temp_label = NULL;
    ui_hum_label = NULL;
    ui_hum_label = NULL;
    ui_moisture_label = NULL;
    ui_moisture_label = NULL;
    ui_lux_label = NULL;
    ui_lux_label = NULL;
    ui_Menu = NULL;
    ui_Menu = NULL;
    ui_menu_list = NULL;
    ui_menu_list = NULL;
    ui_btn_env = NULL;
    ui_btn_env = NULL;
    ui_tempenv = NULL;
    ui_tempenv = NULL;
    ui_lighting_schedule = NULL;
    ui_lighting_schedule = NULL;
    ui_light = NULL;
    ui_light = NULL;
    ui_Display_Settings = NULL;
    ui_Override = NULL;
    ui_disp = NULL;
    ui_disp = NULL;
    ui_Network_Settings = NULL;
    ui_Network_Settings = NULL;
    ui_net = NULL;
    ui_net = NULL;
    ui_env_page = NULL;
    ui_env_page = NULL;
    ui_temp_slider = NULL;
    ui_Soil_moisture_slider = NULL;
    ui_hum_slider = NULL;
    ui_Temp_slider1 = NULL;
    ui_soil_slider = NULL;
    ui_Humidity_slider_ = NULL;
    ui_TempLabel = NULL;
    ui_HumidityLabel = NULL;
    ui_MoistureLabel1 = NULL;
    ui_pHlabel = NULL;
    ui_Soil_moisture_Icon = NULL;
    ui_Temperature_Icon = NULL;
    ui_Humidity_Icon = NULL;
    ui_Bar1 = NULL;
    ui_Image2 = NULL;
    ui_lighting_page = NULL;
    ui_lighting_page = NULL;
    ui_lux_slider = NULL;
    ui_lux_slider = NULL;
    ui_LuxLabel = NULL;
    ui_Image1 = NULL;
    ui_display_page = NULL;
    ui_Override_Page = NULL;
    ui_cold_image = NULL;
    ui_Peltier_Controls = NULL;
    ui_Cold_button = NULL;
    ui_Label3 = NULL;
    ui_heat_image = NULL;
    ui_Peltier_Controls1 = NULL;
    ui_heat_button = NULL;
    ui_Label4 = NULL;
    ui_Mist_Label = NULL;
    ui_mist_image = NULL;
    ui_mist_button = NULL;
    ui_Label5 = NULL;
    ui_UV_Light = NULL;
    ui_light_image = NULL;
    ui_light_level_1 = NULL;
    ui_Label6 = NULL;
    ui_light_level_2 = NULL;
    ui_Label7 = NULL;
    ui_light_level_3 = NULL;
    ui_Label8 = NULL;
    ui_brighter_light = NULL;
    ui_Water_Pump = NULL;
    ui_Water_Pump_Image = NULL;
    ui_water_pump_button = NULL;
    ui_Label9 = NULL;
    ui_btn_back_global = NULL;
    ui_btn_back_global = NULL;
    ui_back = NULL;
    ui_back = NULL;

}
