// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: MenuTFT

#include "../ui.h"

lv_obj_t * ui_back;
lv_obj_t * ui_btn_back_global;
lv_obj_t * ui_display_page;
lv_obj_t * ui_lux_slider;
lv_obj_t * ui_lighting_page;
lv_obj_t * ui_soil_slider;
lv_obj_t * ui_hum_slider;
lv_obj_t * ui_temp_slider;
lv_obj_t * ui_env_page;
lv_obj_t * ui_net;
lv_obj_t * ui_Network_Settings;
lv_obj_t * ui_disp;
lv_obj_t * ui_Display_Settings;
lv_obj_t * ui_light;
lv_obj_t * ui_lighting_schedule;
lv_obj_t * ui_tempenv;
lv_obj_t * ui_btn_env;
lv_obj_t * ui_menu_list;
lv_obj_t * ui_Menu;
lv_obj_t * ui_lux_label;
lv_obj_t * ui_moisture_label;
lv_obj_t * ui_hum_label;
lv_obj_t * ui_temp_label;
lv_obj_t * ui_Dashboard;
lv_obj_t * ui_TabView1;
lv_obj_t * ui_wifistatuslabel;
lv_obj_t * ui_status_bar;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_status_bar = NULL;
lv_obj_t * ui_wifistatuslabel = NULL;
lv_obj_t * ui_TabView1 = NULL;
lv_obj_t * ui_Dashboard = NULL;
lv_obj_t * ui_temp_label = NULL;
lv_obj_t * ui_hum_label = NULL;
lv_obj_t * ui_moisture_label = NULL;
lv_obj_t * ui_lux_label = NULL;
lv_obj_t * ui_Menu = NULL;
lv_obj_t * ui_menu_list = NULL;
lv_obj_t * ui_btn_env = NULL;
lv_obj_t * ui_tempenv = NULL;
lv_obj_t * ui_lighting_schedule = NULL;
lv_obj_t * ui_light = NULL;
lv_obj_t * ui_Display_Settings = NULL;
lv_obj_t * ui_disp = NULL;
lv_obj_t * ui_Network_Settings = NULL;
lv_obj_t * ui_net = NULL;
lv_obj_t * ui_env_page = NULL;
lv_obj_t * ui_temp_slider = NULL;
lv_obj_t * ui_hum_slider = NULL;
lv_obj_t * ui_soil_slider = NULL;
lv_obj_t * ui_TempLabel = NULL;
lv_obj_t * ui_HumidityLabel = NULL;
lv_obj_t * ui_MoistureLabel1 = NULL;
lv_obj_t * ui_Soil_moisture_Icon = NULL;
lv_obj_t * ui_Temperature_Icon = NULL;
lv_obj_t * ui_Humidity_Icon = NULL;
lv_obj_t * ui_Lower_Limit = NULL;
lv_obj_t * ui_Upper_Limit = NULL;
lv_obj_t * ui_LowerMoistLimit = NULL;
lv_obj_t * ui_lighting_page = NULL;
lv_obj_t * ui_lux_slider = NULL;
lv_obj_t * ui_LuxLabel = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_display_page = NULL;
lv_obj_t * ui_btn_back_global = NULL;
lv_obj_t * ui_back = NULL;
// event funtions
void ui_event_btn_env(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_env_page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_lighting_schedule(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_lighting_page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Display_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_menu_list, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_display_page, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_Network_Settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        open_wifi_scanner_cb(e);
        _ui_flag_modify(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_soil_slider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        Moisture_range_slider_changed(e);
    }
}

void ui_event_btn_back_global(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        global_back_cb(e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_status_bar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_status_bar);
    lv_obj_set_width(ui_status_bar, 320);
    lv_obj_set_height(ui_status_bar, 30);
    lv_obj_set_align(ui_status_bar, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_status_bar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifistatuslabel = lv_label_create(ui_status_bar);
    lv_obj_set_width(ui_wifistatuslabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifistatuslabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_wifistatuslabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_wifistatuslabel, "LV_SYMBOL_WIFI");

    ui_TabView1 = lv_tabview_create(ui_Screen1, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_TabView1, 480);
    lv_obj_set_height(ui_TabView1, 290);
    lv_obj_set_align(ui_TabView1, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_TabView1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dashboard = lv_tabview_add_tab(ui_TabView1, "Dashboard");

    ui_temp_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_temp_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp_label, 0);
    lv_obj_set_y(ui_temp_label, 20);
    lv_obj_set_align(ui_temp_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_temp_label, "Temp: --.- °F");

    ui_hum_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_hum_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_hum_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_hum_label, 0);
    lv_obj_set_y(ui_hum_label, 60);
    lv_obj_set_align(ui_hum_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_hum_label, "Humidity: -- %");

    ui_moisture_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_moisture_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_moisture_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_moisture_label, 0);
    lv_obj_set_y(ui_moisture_label, 100);
    lv_obj_set_align(ui_moisture_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_moisture_label, "Moisture: -- %");

    ui_lux_label = lv_label_create(ui_Dashboard);
    lv_obj_set_width(ui_lux_label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lux_label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lux_label, 0);
    lv_obj_set_y(ui_lux_label, 140);
    lv_obj_set_align(ui_lux_label, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_lux_label, "Light: -- lux");

    ui_Menu = lv_tabview_add_tab(ui_TabView1, "Menu");

    ui_menu_list = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_menu_list);
    lv_obj_set_width(ui_menu_list, lv_pct(100));
    lv_obj_set_height(ui_menu_list, lv_pct(100));
    lv_obj_set_align(ui_menu_list, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_menu_list, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_menu_list, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_menu_list, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_scroll_dir(ui_menu_list, LV_DIR_VER);

    ui_btn_env = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_btn_env, 50);
    lv_obj_set_width(ui_btn_env, lv_pct(100));
    lv_obj_set_align(ui_btn_env, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btn_env, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_env, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempenv = lv_label_create(ui_btn_env);
    lv_obj_set_width(ui_tempenv, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempenv, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_tempenv, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempenv, "Temperature & Environment");

    ui_lighting_schedule = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_lighting_schedule, 50);
    lv_obj_set_width(ui_lighting_schedule, lv_pct(100));
    lv_obj_set_x(ui_lighting_schedule, 8);
    lv_obj_set_y(ui_lighting_schedule, 29);
    lv_obj_set_align(ui_lighting_schedule, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lighting_schedule, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_lighting_schedule, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_light = lv_label_create(ui_lighting_schedule);
    lv_obj_set_width(ui_light, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_light, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_light, LV_ALIGN_CENTER);
    lv_label_set_text(ui_light, "Lighting Schedule");

    ui_Display_Settings = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_Display_Settings, 50);
    lv_obj_set_width(ui_Display_Settings, lv_pct(100));
    lv_obj_set_x(ui_Display_Settings, 8);
    lv_obj_set_y(ui_Display_Settings, 29);
    lv_obj_set_align(ui_Display_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Display_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Display_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_disp = lv_label_create(ui_Display_Settings);
    lv_obj_set_width(ui_disp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_disp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_disp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_disp, "Display Settings");

    ui_Network_Settings = lv_btn_create(ui_menu_list);
    lv_obj_set_height(ui_Network_Settings, 50);
    lv_obj_set_width(ui_Network_Settings, lv_pct(100));
    lv_obj_set_x(ui_Network_Settings, 8);
    lv_obj_set_y(ui_Network_Settings, 29);
    lv_obj_set_align(ui_Network_Settings, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Network_Settings, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Network_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_net = lv_label_create(ui_Network_Settings);
    lv_obj_set_width(ui_net, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_net, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_net, LV_ALIGN_CENTER);
    lv_label_set_text(ui_net, "Network Settings");

    ui_env_page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_env_page);
    lv_obj_set_width(ui_env_page, lv_pct(100));
    lv_obj_set_height(ui_env_page, lv_pct(100));
    lv_obj_set_align(ui_env_page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_env_page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_env_page, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_temp_slider = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_temp_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_temp_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_temp_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_temp_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_temp_slider, 150);
    lv_obj_set_height(ui_temp_slider, 10);
    lv_obj_set_x(ui_temp_slider, 0);
    lv_obj_set_y(ui_temp_slider, -50);
    lv_obj_set_align(ui_temp_slider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_temp_slider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_temp_slider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_hum_slider = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_hum_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_hum_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_hum_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_hum_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_hum_slider, 150);
    lv_obj_set_height(ui_hum_slider, 10);
    lv_obj_set_x(ui_hum_slider, 0);
    lv_obj_set_y(ui_hum_slider, 10);
    lv_obj_set_align(ui_hum_slider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_hum_slider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_hum_slider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_soil_slider = lv_slider_create(ui_env_page);
    lv_slider_set_mode(ui_soil_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_soil_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_soil_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_soil_slider, 100,
                                                                                                LV_ANIM_OFF);
    lv_obj_set_width(ui_soil_slider, 150);
    lv_obj_set_height(ui_soil_slider, 10);
    lv_obj_set_x(ui_soil_slider, 0);
    lv_obj_set_y(ui_soil_slider, 70);
    lv_obj_set_align(ui_soil_slider, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_soil_slider, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_soil_slider, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);

    ui_TempLabel = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_TempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempLabel, 0);
    lv_obj_set_y(ui_TempLabel, -10);
    lv_obj_set_align(ui_TempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempLabel, "Temperature ");

    ui_HumidityLabel = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_HumidityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HumidityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HumidityLabel, 0);
    lv_obj_set_y(ui_HumidityLabel, 50);
    lv_obj_set_align(ui_HumidityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HumidityLabel, "Humidity");

    ui_MoistureLabel1 = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_MoistureLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MoistureLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MoistureLabel1, 0);
    lv_obj_set_y(ui_MoistureLabel1, -70);
    lv_obj_set_align(ui_MoistureLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MoistureLabel1, "Soil Moisture");

    ui_Soil_moisture_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Soil_moisture_Icon, &ui_img_waterdroplet_white_png);
    lv_obj_set_width(ui_Soil_moisture_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Soil_moisture_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Soil_moisture_Icon, 90);
    lv_obj_set_y(ui_Soil_moisture_Icon, -50);
    lv_obj_set_align(ui_Soil_moisture_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Soil_moisture_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Soil_moisture_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Soil_moisture_Icon, 40);

    ui_Temperature_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Temperature_Icon, &ui_img_temp_icon_png);
    lv_obj_set_width(ui_Temperature_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temperature_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temperature_Icon, 90);
    lv_obj_set_y(ui_Temperature_Icon, 10);
    lv_obj_set_align(ui_Temperature_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Temperature_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Temperature_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Temperature_Icon, 10);

    ui_Humidity_Icon = lv_img_create(ui_env_page);
    lv_img_set_src(ui_Humidity_Icon, &ui_img_humidity_icon_png);
    lv_obj_set_width(ui_Humidity_Icon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Humidity_Icon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Humidity_Icon, 90);
    lv_obj_set_y(ui_Humidity_Icon, 70);
    lv_obj_set_align(ui_Humidity_Icon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Humidity_Icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Humidity_Icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Humidity_Icon, 10);

    ui_Lower_Limit = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_Lower_Limit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Lower_Limit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Lower_Limit, 170);
    lv_obj_set_y(ui_Lower_Limit, -99);
    lv_obj_set_align(ui_Lower_Limit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Lower_Limit, "Lower Limit");

    ui_Upper_Limit = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_Upper_Limit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Upper_Limit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Upper_Limit, -170);
    lv_obj_set_y(ui_Upper_Limit, -99);
    lv_obj_set_align(ui_Upper_Limit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Upper_Limit, "Upper Limit");

    ui_LowerMoistLimit = lv_label_create(ui_env_page);
    lv_obj_set_width(ui_LowerMoistLimit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LowerMoistLimit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LowerMoistLimit, 115);
    lv_obj_set_y(ui_LowerMoistLimit, -50);
    lv_obj_set_align(ui_LowerMoistLimit, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LowerMoistLimit, "0%");

    ui_lighting_page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_lighting_page);
    lv_obj_set_width(ui_lighting_page, lv_pct(100));
    lv_obj_set_height(ui_lighting_page, lv_pct(100));
    lv_obj_set_align(ui_lighting_page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_lighting_page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_lighting_page, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_lux_slider = lv_slider_create(ui_lighting_page);
    lv_slider_set_mode(ui_lux_slider, LV_SLIDER_MODE_RANGE);
    lv_slider_set_value(ui_lux_slider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_lux_slider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_lux_slider, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_lux_slider, 150);
    lv_obj_set_height(ui_lux_slider, 10);
    lv_obj_set_align(ui_lux_slider, LV_ALIGN_CENTER);

    ui_LuxLabel = lv_label_create(ui_lighting_page);
    lv_obj_set_width(ui_LuxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LuxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LuxLabel, 0);
    lv_obj_set_y(ui_LuxLabel, -20);
    lv_obj_set_align(ui_LuxLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LuxLabel, "Lux");

    ui_Image1 = lv_img_create(ui_lighting_page);
    lv_img_set_src(ui_Image1, &ui_img_sun_white_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 110);
    lv_obj_set_y(ui_Image1, 0);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image1, 20);

    ui_display_page = lv_obj_create(ui_Menu);
    lv_obj_remove_style_all(ui_display_page);
    lv_obj_set_width(ui_display_page, lv_pct(100));
    lv_obj_set_height(ui_display_page, lv_pct(100));
    lv_obj_set_x(ui_display_page, 0);
    lv_obj_set_y(ui_display_page, 2);
    lv_obj_set_align(ui_display_page, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_display_page, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_display_page, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_btn_back_global = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_btn_back_global, 100);
    lv_obj_set_height(ui_btn_back_global, 22);
    lv_obj_set_x(ui_btn_back_global, 3);
    lv_obj_set_y(ui_btn_back_global, 3);
    lv_obj_add_flag(ui_btn_back_global, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_btn_back_global, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_back = lv_label_create(ui_btn_back_global);
    lv_obj_set_width(ui_back, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_back, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_back, LV_ALIGN_CENTER);
    lv_label_set_text(ui_back, "< Back");

    lv_obj_add_event_cb(ui_btn_env, ui_event_btn_env, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_lighting_schedule, ui_event_lighting_schedule, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Display_Settings, ui_event_Display_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Network_Settings, ui_event_Network_Settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_soil_slider, ui_event_soil_slider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_btn_back_global, ui_event_btn_back_global, LV_EVENT_ALL, NULL);
    ui_status_bar = ui_status_bar;
    ui_wifistatuslabel = ui_wifistatuslabel;
    ui_TabView1 = ui_TabView1;
    ui_Dashboard = ui_Dashboard;
    ui_temp_label = ui_temp_label;
    ui_hum_label = ui_hum_label;
    ui_moisture_label = ui_moisture_label;
    ui_lux_label = ui_lux_label;
    ui_Menu = ui_Menu;
    ui_menu_list = ui_menu_list;
    ui_btn_env = ui_btn_env;
    ui_tempenv = ui_tempenv;
    ui_lighting_schedule = ui_lighting_schedule;
    ui_light = ui_light;
    ui_Display_Settings = ui_Display_Settings;
    ui_disp = ui_disp;
    ui_Network_Settings = ui_Network_Settings;
    ui_net = ui_net;
    ui_env_page = ui_env_page;
    ui_temp_slider = ui_temp_slider;
    ui_hum_slider = ui_hum_slider;
    ui_soil_slider = ui_soil_slider;
    ui_lighting_page = ui_lighting_page;
    ui_lux_slider = ui_lux_slider;
    ui_display_page = ui_display_page;
    ui_btn_back_global = ui_btn_back_global;
    ui_back = ui_back;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_status_bar = NULL;
    ui_status_bar = NULL;
    ui_wifistatuslabel = NULL;
    ui_wifistatuslabel = NULL;
    ui_TabView1 = NULL;
    ui_TabView1 = NULL;
    ui_Dashboard = NULL;
    ui_Dashboard = NULL;
    ui_temp_label = NULL;
    ui_temp_label = NULL;
    ui_hum_label = NULL;
    ui_hum_label = NULL;
    ui_moisture_label = NULL;
    ui_moisture_label = NULL;
    ui_lux_label = NULL;
    ui_lux_label = NULL;
    ui_Menu = NULL;
    ui_Menu = NULL;
    ui_menu_list = NULL;
    ui_menu_list = NULL;
    ui_btn_env = NULL;
    ui_btn_env = NULL;
    ui_tempenv = NULL;
    ui_tempenv = NULL;
    ui_lighting_schedule = NULL;
    ui_lighting_schedule = NULL;
    ui_light = NULL;
    ui_light = NULL;
    ui_Display_Settings = NULL;
    ui_Display_Settings = NULL;
    ui_disp = NULL;
    ui_disp = NULL;
    ui_Network_Settings = NULL;
    ui_Network_Settings = NULL;
    ui_net = NULL;
    ui_net = NULL;
    ui_env_page = NULL;
    ui_env_page = NULL;
    ui_temp_slider = NULL;
    ui_temp_slider = NULL;
    ui_hum_slider = NULL;
    ui_hum_slider = NULL;
    ui_soil_slider = NULL;
    ui_soil_slider = NULL;
    ui_TempLabel = NULL;
    ui_HumidityLabel = NULL;
    ui_MoistureLabel1 = NULL;
    ui_Soil_moisture_Icon = NULL;
    ui_Temperature_Icon = NULL;
    ui_Humidity_Icon = NULL;
    ui_Lower_Limit = NULL;
    ui_Upper_Limit = NULL;
    ui_LowerMoistLimit = NULL;
    ui_lighting_page = NULL;
    ui_lighting_page = NULL;
    ui_lux_slider = NULL;
    ui_lux_slider = NULL;
    ui_LuxLabel = NULL;
    ui_Image1 = NULL;
    ui_display_page = NULL;
    ui_display_page = NULL;
    ui_btn_back_global = NULL;
    ui_btn_back_global = NULL;
    ui_back = NULL;
    ui_back = NULL;

}
